# Exploring NHL API to get Data for Expected Goals Model

In [17]:
import pandas as pd
import requests
import json

In [24]:
url = 'https://api-web.nhle.com/v1/club-schedule/OTT/month/2025-03'

# Send GET request to fetch game data
response = requests.get(url)

# Check if reponse was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Pretty print the JSON with an indentation of 4 spaces
    pretty_json = json.dumps(data, indent=4)
    # Output data
    #print(pretty_json)

    # Step 3: Flatten the data
    # We'll normalize both top-level and nested dictionaries
    #df = pd.json_normalize(data, sep="_")
    
else:
    print(f"Error: {response.status_code}")

In [21]:
df

,previousMonth,currentMonth,nextMonth,calendarUrl,clubTimezone,clubUTCOffset,games
0,2023-10,2023-11,2023-12,https://nhl.ecal.com/maple-leafs,America/Toronto,-04:00,"[{'id': 2023020145, 'season': 20232024, 'gameT..."

In [ ]:
url = 'https://statsapi.web.nhl.com/api/v1/game/2023020001/feed/live'

# Send GET request to fetch game data
response = requests.get(url)

# Check if reponse was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Pretty print the JSON with an indentation of 4 spaces
    pretty_json = json.dumps(data, indent=4)
    # Output data
    #print(pretty_json)

    # Step 3: Flatten the data
    # We'll normalize both top-level and nested dictionaries
    #df = pd.json_normalize(data, sep="_")
    
else:
    print(f"Error: {response.status_code}")

ConnectionError: HTTPSConnectionPool(host='statsapi.web.nhl.com', port=443): Max retries exceeded with url: /api/v1/game/2023020001/feed/live (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x15ad3eb50>: Failed to resolve 'statsapi.web.nhl.com' ([Errno 8] nodename nor servname provided, or not known)"))

## Display

In [2]:
def adjust_df_display(dimension, action):
    """This function when called adjusts the output display of pandas dataframes. It either changes the max_columns or max_rows to infinite or resets those
    values to their default display limits.

    Args:
        dimension (string): Display dimension of a dataframe to alter; should be either "columns" or "rows".
        action (string): Action to be carried out on display settings; should be either "max" or "limit".
    """
    if dimension == "columns" and action == "max":
        pd.set_option('display.max_columns', None)
    elif dimension == "rows" and action == "max":
        pd.set_option('display.max_rows', None)
    elif dimension == "columns" and action == "limit":
        pd.reset_option('max_columns')
    else:
        pd.reset_option('max_rows')

In [11]:
adjust_df_display("columns", "max")
adjust_df_display("rows", "max")

## API Data

In [32]:
url = 'https://api-web.nhle.com/v1/gamecenter/2024020954/play-by-play'

# Send GET request to fetch game data
response = requests.get(url)

# Check if reponse was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Pretty print the JSON with an indentation of 4 spaces
    pretty_json = json.dumps(data, indent=4)
    # Output data
    #print(pretty_json)
    
    # Step 2: Extract the plays list
    plays = data.get("plays", [])

    # Step 3: Flatten the data
    # We'll normalize both top-level and nested dictionaries
    df = pd.json_normalize(plays, sep="_")
    
else:
    print(f"Error: {response.status_code}")

In [33]:
df = pd.json_normalize(plays, sep='_')
df.head()

,eventId,timeInPeriod,timeRemaining,situationCode,homeTeamDefendingSide,typeCode,typeDescKey,sortOrder,periodDescriptor_number,periodDescriptor_periodType,periodDescriptor_maxRegulationPeriods,details_eventOwnerTeamId,details_losingPlayerId,details_winningPlayerId,details_xCoord,details_yCoord,details_zoneCode,details_shotType,details_shootingPlayerId,details_goalieInNetId,details_awaySOG,details_homeSOG,details_reason,details_hittingPlayerId,details_hitteePlayerId,details_playerId,details_blockingPlayerId,details_secondaryReason,details_typeCode,details_descKey,details_duration,details_committedByPlayerId,details_drawnByPlayerId,pptReplayUrl,details_scoringPlayerId,details_scoringPlayerTotal,details_assist1PlayerId,details_assist1PlayerTotal,details_awayScore,details_homeScore,details_highlightClipSharingUrl,details_highlightClipSharingUrlFr,details_highlightClip,details_highlightClipFr,details_discreteClip,details_discreteClipFr,details_assist2PlayerId,details_assist2PlayerTotal
0,52,00:00,20:00,1551,left,520,period-start,8,1,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51,00:00,20:00,1551,left,502,faceoff,11,1,REG,3,28.0,8482116.0,8477505.0,0.0,0.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,103,00:09,19:51,1551,left,506,shot-on-goal,12,1,REG,3,28.0,NaN,NaN,-56.0,2.0,O,wrist,8477505.0,8476999.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8,00:10,19:50,1551,left,516,stoppage,13,1,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,goalie-stopped-after-sog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53,00:10,19:50,1551,left,502,faceoff,15,1,REG,3,9.0,8477505.0,8481596.0,-69.0,-22.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Event Type: 'goal'

In [27]:
df[df['typeDescKey'] == 'goal']

,eventId,timeInPeriod,timeRemaining,situationCode,homeTeamDefendingSide,typeCode,typeDescKey,sortOrder,periodDescriptor_number,periodDescriptor_periodType,periodDescriptor_maxRegulationPeriods,details_eventOwnerTeamId,details_losingPlayerId,details_winningPlayerId,details_xCoord,details_yCoord,details_zoneCode,details_shotType,details_shootingPlayerId,details_goalieInNetId,details_awaySOG,details_homeSOG,details_reason,details_hittingPlayerId,details_hitteePlayerId,details_playerId,details_blockingPlayerId,details_secondaryReason,details_typeCode,details_descKey,details_duration,details_committedByPlayerId,details_drawnByPlayerId,pptReplayUrl,details_scoringPlayerId,details_scoringPlayerTotal,details_assist1PlayerId,details_assist1PlayerTotal,details_awayScore,details_homeScore,details_highlightClipSharingUrl,details_highlightClipSharingUrlFr,details_highlightClip,details_highlightClipFr,details_discreteClip,details_discreteClipFr,details_assist2PlayerId,details_assist2PlayerTotal
57,264,11:05,08:55,1541,left,505,goal,171,1,REG,3,9.0,NaN,NaN,74.0,5.0,O,wrist,NaN,8477970.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8481596.0,12.0,8482092.0,10.0,0.0,1.0,https://nhl.com/video/sjs-ott-pinto-scores-shg...,https://nhl.com/fr/video/sjs-ott-pinto-marque-...,6.369509e+12,6.369509e+12,6.369509e+12,6.369507e+12,NaN,NaN
125,579,05:17,14:43,1541,right,505,goal,350,2,REG,3,28.0,NaN,NaN,84.0,23.0,O,wrist,NaN,8476999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8475726.0,22.0,8484227.0,18.0,1.0,1.0,https://nhl.com/video/sjs-ott-toffoli-scores-g...,https://nhl.com/fr/video/sjs-ott-toffoli-marqu...,6.369510e+12,6.369508e+12,NaN,NaN,8484801.0,25.0
157,641,09:47,10:13,1541,right,505,goal,406,2,REG,3,28.0,NaN,NaN,37.0,4.0,O,slap,NaN,8476999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8480043.0,5.0,8477505.0,18.0,2.0,1.0,https://nhl.com/video/sjs-ott-liljegren-scores...,https://nhl.com/fr/video/sjs-ott-liljegren-mar...,6.369510e+12,6.369509e+12,6.369508e+12,6.369510e+12,8480011.0,5.0
228,832,01:26,18:34,1351,left,505,goal,551,3,REG,3,9.0,NaN,NaN,56.0,-17.0,O,wrist,NaN,8477970.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8480801.0,22.0,8482116.0,42.0,2.0,2.0,https://nhl.com/video/sjs-ott-tkachuk-scores-p...,https://nhl.com/fr/video/sjs-ott-tkachuk-marqu...,6.369512e+12,6.369512e+12,6.369510e+12,6.369509e+12,8482105.0,31.0
234,844,03:00,17:00,1551,left,505,goal,563,3,REG,3,9.0,NaN,NaN,77.0,-14.0,O,wrist,NaN,8477970.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8482116.0,19.0,8482092.0,11.0,2.0,3.0,https://nhl.com/video/sjs-ott-stutzle-scores-g...,https://nhl.com/fr/video/sjs-ott-stutzle-marqu...,6.369512e+12,6.369510e+12,6.369510e+12,6.369510e+12,NaN,NaN
278,937,08:31,11:29,1551,left,505,goal,661,3,REG,3,9.0,NaN,NaN,85.0,7.0,O,wrist,NaN,8477970.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8474102.0,2.0,8478469.0,24.0,2.0,4.0,https://nhl.com/video/sjs-ott-perron-scores-go...,https://nhl.com/fr/video/sjs-ott-perron-marque...,6.369512e+12,6.369510e+12,6.369513e+12,6.369512e+12,8480208.0,31.0
327,1071,18:33,01:27,0641,left,505,goal,802,3,REG,3,28.0,NaN,NaN,-80.0,-8.0,O,wrist,NaN,8476999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8484227.0,10.0,8482667.0,31.0,3.0,4.0,https://nhl.com/video/sjs-ott-smith-scores-ppg...,https://nhl.com/fr/video/will-smith-with-a-pow...,6.369511e+12,6.369511e+12,6.369512e+12,6.369511e+12,8484801.0,26.0
329,1078,19:00,01:00,0651,left,505,goal,808,3,REG,3,9.0,NaN,NaN,21.0,-30.0,N,wrist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://wsr.nhle.com/sprites/20242025/20240209...,8478020.0,6.0,8482245.0,7.0,3.0,5.0,https://nhl.com/video/sjs-ott-amadio-scores-em...,https://nhl.com/fr/video/sjs-ott-amadio-ott-ma...,6.369513e+12,6.369512e+12,6.369511e+12,6.369513e+12,NaN,NaN

In [29]:
df[df['typeDescKey'] == 'shot-on-goal'].head()

,eventId,timeInPeriod,timeRemaining,situationCode,homeTeamDefendingSide,typeCode,typeDescKey,sortOrder,periodDescriptor_number,periodDescriptor_periodType,periodDescriptor_maxRegulationPeriods,details_eventOwnerTeamId,details_losingPlayerId,details_winningPlayerId,details_xCoord,details_yCoord,details_zoneCode,details_shotType,details_shootingPlayerId,details_goalieInNetId,details_awaySOG,details_homeSOG,details_reason,details_hittingPlayerId,details_hitteePlayerId,details_playerId,details_blockingPlayerId,details_secondaryReason,details_typeCode,details_descKey,details_duration,details_committedByPlayerId,details_drawnByPlayerId,pptReplayUrl,details_scoringPlayerId,details_scoringPlayerTotal,details_assist1PlayerId,details_assist1PlayerTotal,details_awayScore,details_homeScore,details_highlightClipSharingUrl,details_highlightClipSharingUrlFr,details_highlightClip,details_highlightClipFr,details_discreteClip,details_discreteClipFr,details_assist2PlayerId,details_assist2PlayerTotal
2,103,00:09,19:51,1551,left,506,shot-on-goal,12,1,REG,3,28.0,NaN,NaN,-56.0,2.0,O,wrist,8477505.0,8476999.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,131,02:11,17:49,1551,left,506,shot-on-goal,40,1,REG,3,28.0,NaN,NaN,-56.0,11.0,O,wrist,8480848.0,8476999.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,140,02:57,17:03,1551,left,506,shot-on-goal,52,1,REG,3,28.0,NaN,NaN,-63.0,-16.0,O,wrist,8484911.0,8476999.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,148,03:34,16:26,1551,left,506,shot-on-goal,61,1,REG,3,9.0,NaN,NaN,51.0,-18.0,O,wrist,8480801.0,8477970.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,155,03:59,16:01,1551,left,506,shot-on-goal,67,1,REG,3,28.0,NaN,NaN,-54.0,32.0,O,wrist,8482144.0,8476999.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df[df['typeDescKey'] == 'missed-shot'].head()

,eventId,timeInPeriod,timeRemaining,situationCode,homeTeamDefendingSide,typeCode,typeDescKey,sortOrder,periodDescriptor_number,periodDescriptor_periodType,periodDescriptor_maxRegulationPeriods,details_eventOwnerTeamId,details_losingPlayerId,details_winningPlayerId,details_xCoord,details_yCoord,details_zoneCode,details_shotType,details_shootingPlayerId,details_goalieInNetId,details_awaySOG,details_homeSOG,details_reason,details_hittingPlayerId,details_hitteePlayerId,details_playerId,details_blockingPlayerId,details_secondaryReason,details_typeCode,details_descKey,details_duration,details_committedByPlayerId,details_drawnByPlayerId,pptReplayUrl,details_scoringPlayerId,details_scoringPlayerTotal,details_assist1PlayerId,details_assist1PlayerTotal,details_awayScore,details_homeScore,details_highlightClipSharingUrl,details_highlightClipSharingUrlFr,details_highlightClip,details_highlightClipFr,details_discreteClip,details_discreteClipFr,details_assist2PlayerId,details_assist2PlayerTotal
6,115,01:09,18:51,1551,left,507,missed-shot,26,1,REG,3,9.0,NaN,NaN,42.0,38.0,O,wrist,8480801.0,8477970.0,NaN,NaN,high-and-wide-left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,116,01:12,18:48,1551,left,507,missed-shot,28,1,REG,3,9.0,NaN,NaN,54.0,-40.0,O,wrist,8482245.0,8477970.0,NaN,NaN,wide-left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,186,06:06,13:54,1551,left,507,missed-shot,98,1,REG,3,28.0,NaN,NaN,-50.0,-2.0,O,wrist,8477505.0,8476999.0,NaN,NaN,wide-right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,57,07:26,12:34,1551,left,507,missed-shot,113,1,REG,3,28.0,NaN,NaN,-71.0,-11.0,O,tip-in,8475726.0,8476999.0,NaN,NaN,wide-right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,208,07:41,12:19,1551,left,507,missed-shot,122,1,REG,3,28.0,NaN,NaN,-86.0,8.0,O,backhand,8479316.0,8476999.0,NaN,NaN,wide-left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
url = 'https://api-web.nhle.com/v1/wsc/game-story/2023020204'

# Send GET request to fetch game data
response = requests.get(url)

# Check if reponse was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Pretty print the JSON with an indentation of 4 spaces
    pretty_json = json.dumps(data, indent=4)
    # Output data
    print(pretty_json)
    
    # Step 2: Extract the plays list
    #plays = data.get("plays", [])

    # Step 3: Flatten the data
    # We'll normalize both top-level and nested dictionaries
    #df = pd.json_normalize(plays, sep="_")
    
else:
    print(f"Error: {response.status_code}")

{
    "id": 2023020204,
    "season": 20232024,
    "gameType": 2,
    "limitedScoring": false,
    "gameDate": "2023-11-10",
    "venue": {
        "default": "KeyBank Center"
    },
    "venueLocation": {
        "default": "Buffalo"
    },
    "startTimeUTC": "2023-11-11T00:00:00Z",
    "easternUTCOffset": "-05:00",
    "venueUTCOffset": "-05:00",
    "venueTimezone": "America/New_York",
    "tvBroadcasts": [
        {
            "id": 28,
            "market": "H",
            "countryCode": "US",
            "network": "MSG-B",
            "sequenceNumber": 383
        },
        {
            "id": 284,
            "market": "N",
            "countryCode": "CA",
            "network": "SN1",
            "sequenceNumber": 102
        },
        {
            "id": 363,
            "market": "A",
            "countryCode": "US",
            "network": "BSWI",
            "sequenceNumber": 403
        },
        {
            "id": 395,
            "market": "A",
            "countryCode": "US",
            "network": "BSNX",
            "sequenceNumber": 385
        }
    ],
    "gameState": "OFF",
    "gameScheduleState": "OK",
    "awayTeam": {
        "id": 30,
        "name": {
            "default": "Wild"
        },
        "abbrev": "MIN",
        "placeName": {
            "default": "Minnesota"
        },
        "score": 2,
        "sog": 35,
        "logo": "https://assets.nhle.com/logos/nhl/svg/MIN_light.svg"
    },
    "homeTeam": {
        "id": 7,
        "name": {
            "default": "Sabres"
        },
        "abbrev": "BUF",
        "placeName": {
            "default": "Buffalo"
        },
        "score": 3,
        "sog": 25,
        "logo": "https://assets.nhle.com/logos/nhl/svg/BUF_light.svg"
    },
    "shootoutInUse": true,
    "maxPeriods": 5,
    "regPeriods": 3,
    "otInUse": true,
    "tiesInUse": false,
    "summary": {
        "scoring": [
            {
                "periodDescriptor": {
                    "number": 1,
                    "periodType": "REG",
                    "maxRegulationPeriods": 3
                },
                "goals": [
                    {
                        "situationCode": "1551",
                        "eventId": 381,
                        "strength": "ev",
                        "playerId": 8480035,
                        "firstName": {
                            "default": "Henri"
                        },
                        "lastName": {
                            "default": "Jokiharju"
                        },
                        "name": {
                            "default": "H. Jokiharju"
                        },
                        "teamAbbrev": {
                            "default": "BUF"
                        },
                        "headshot": "https://assets.nhle.com/mugs/nhl/20232024/BUF/8480035.png",
                        "highlightClipSharingUrl": "https://nhl.com/video/min-buf-jokiharju-scores-goal-against-wild-6340906550112",
                        "highlightClip": 6340906550112,
                        "goalsToDate": 2,
                        "awayScore": 0,
                        "homeScore": 1,
                        "leadingTeamAbbrev": {
                            "default": "BUF"
                        },
                        "timeInPeriod": "18:02",
                        "shotType": "slap",
                        "goalModifier": "none",
                        "assists": [
                            {
                                "playerId": 8482671,
                                "firstName": {
                                    "default": "Owen"
                                },
                                "lastName": {
                                    "default": "Power"
                                },
                                "name": {
                                    "default": "O. Power"
                                },
                                "assistsToDate": 7,
                                "sweaterNumber": 25
                            }
                        ],
                        "homeTeamDefendingSide": "left",
                        "isHome": true
                    },
                    {
                        "situationCode": "1541",
                        "eventId": 399,
                        "strength": "pp",
                        "playerId": 8478864,
                        "firstName": {
                            "default": "Kirill"
                        },
                        "lastName": {
                            "default": "Kaprizov"
                        },
                        "name": {
                            "default": "K. Kaprizov"
                        },
                        "teamAbbrev": {
                            "default": "MIN"
                        },
                        "headshot": "https://assets.nhle.com/mugs/nhl/20232024/MIN/8478864.png",
                        "highlightClipSharingUrl": "https://nhl.com/video/min-buf-kaprizov-scores-goal-against-sabres-6340908991112",
                        "highlightClip": 6340908991112,
                        "goalsToDate": 5,
                        "awayScore": 1,
                        "homeScore": 1,
                        "timeInPeriod": "19:30",
                        "shotType": "slap",
                        "goalModifier": "none",
                        "assists": [
                            {
                                "playerId": 8481557,
                                "firstName": {
                                    "default": "Matt"
                                },
                                "lastName": {
                                    "default": "Boldy"
                                },
                                "name": {
                                    "default": "M. Boldy"
                                },
                                "assistsToDate": 6,
                                "sweaterNumber": 12
                            },
                            {
                                "playerId": 8475692,
                                "firstName": {
                                    "default": "Mats"
                                },
                                "lastName": {
                                    "default": "Zuccarello"
                                },
                                "name": {
                                    "default": "M. Zuccarello"
                                },
                                "assistsToDate": 11,
                                "sweaterNumber": 36
                            }
                        ],
                        "homeTeamDefendingSide": "left",
                        "isHome": false
                    }
                ]
            },
            {
                "periodDescriptor": {
                    "number": 2,
                    "periodType": "REG",
                    "maxRegulationPeriods": 3
                },
                "goals": [
                    {
                        "situationCode": "1551",
                        "eventId": 743,
                        "strength": "ev",
                        "playerId": 8475784,
                        "firstName": {
                            "default": "Jeff"
                        },
                        "lastName": {
                            "default": "Skinner"
                        },
                        "name": {
                            "default": "J. Skinner"
                        },
                        "teamAbbrev": {
                            "default": "BUF"
                        },
                        "headshot": "https://assets.nhle.com/mugs/nhl/20232024/BUF/8475784.png",
                        "goalsToDate": 7,
                        "awayScore": 1,
                        "homeScore": 2,
                        "leadingTeamAbbrev": {
                            "default": "BUF"
                        },
                        "timeInPeriod": "19:02",
                        "shotType": "wrist",
                        "goalModifier": "none",
                        "assists": [
                            {
                                "playerId": 8482175,
                                "firstName": {
                                    "default": "JJ"
                                },
                                "lastName": {
                                    "default": "Peterka"
                                },
                                "name": {
                                    "default": "J. Peterka"
                                },
                                "assistsToDate": 4,
                                "sweaterNumber": 77
                            }
                        ],
                        "homeTeamDefendingSide": "right",
                        "isHome": true
                    }
                ]
            },
            {
                "periodDescriptor": {
                    "number": 3,
                    "periodType": "REG",
                    "maxRegulationPeriods": 3
                },
                "goals": [
                    {
                        "situationCode": "1551",
                        "eventId": 795,
                        "strength": "ev",
                        "playerId": 8482175,
                        "firstName": {
                            "default": "JJ"
                        },
                        "lastName": {
                            "default": "Peterka"
                        },
                        "name": {
                            "default": "J. Peterka"
                        },
                        "teamAbbrev": {
                            "default": "BUF"
                        },
                        "headshot": "https://assets.nhle.com/mugs/nhl/20232024/BUF/8482175.png",
                        "highlightClipSharingUrl": "https://nhl.com/video/min-buf-peterka-scores-goal-against-wild-6340912512112",
                        "highlightClip": 6340912512112,
                        "goalsToDate": 6,
                        "awayScore": 1,
                        "homeScore": 3,
                        "leadingTeamAbbrev": {
                            "default": "BUF"
                        },
                        "timeInPeriod": "03:33",
                        "shotType": "snap",
                        "goalModifier": "none",
                        "assists": [
                            {
                                "playerId": 8479420,
                                "firstName": {
                                    "default": "Tage"
                                },
                                "lastName": {
                                    "default": "Thompson"
                                },
                                "name": {
                                    "default": "T. Thompson"
                                },
                                "assistsToDate": 6,
                                "sweaterNumber": 72
                            },
                            {
                                "playerId": 8475784,
                                "firstName": {
                                    "default": "Jeff"
                                },
                                "lastName": {
                                    "default": "Skinner"
                                },
                                "name": {
                                    "default": "J. Skinner"
                                },
                                "assistsToDate": 6,
                                "sweaterNumber": 53
                            }
                        ],
                        "homeTeamDefendingSide": "left",
                        "isHome": true
                    },
                    {
                        "situationCode": "1541",
                        "eventId": 886,
                        "strength": "pp",
                        "playerId": 8478493,
                        "firstName": {
                            "default": "Joel"
                        },
                        "lastName": {
                            "default": "Eriksson Ek"
                        },
                        "name": {
                            "default": "J. Eriksson Ek"
                        },
                        "teamAbbrev": {
                            "default": "MIN"
                        },
                        "headshot": "https://assets.nhle.com/mugs/nhl/20232024/MIN/8478493.png",
                        "highlightClipSharingUrl": "https://nhl.com/video/min-buf-eriksson-ek-scores-goal-against-sabres-6340911091112",
                        "highlightClip": 6340911091112,
                        "goalsToDate": 8,
                        "awayScore": 2,
                        "homeScore": 3,
                        "leadingTeamAbbrev": {
                            "default": "BUF"
                        },
                        "timeInPeriod": "12:27",
                        "shotType": "slap",
                        "goalModifier": "none",
                        "assists": [
                            {
                                "playerId": 8478864,
                                "firstName": {
                                    "default": "Kirill"
                                },
                                "lastName": {
                                    "default": "Kaprizov"
                                },
                                "name": {
                                    "default": "K. Kaprizov"
                                },
                                "assistsToDate": 9,
                                "sweaterNumber": 97
                            },
                            {
                                "playerId": 8475692,
                                "firstName": {
                                    "default": "Mats"
                                },
                                "lastName": {
                                    "default": "Zuccarello"
                                },
                                "name": {
                                    "default": "M. Zuccarello"
                                },
                                "assistsToDate": 12,
                                "sweaterNumber": 36
                            }
                        ],
                        "homeTeamDefendingSide": "left",
                        "isHome": false
                    }
                ]
            }
        ],
        "shootout": [],
        "threeStars": [
            {
                "star": 1,
                "playerId": 8482221,
                "teamAbbrev": "BUF",
                "headshot": "https://assets.nhle.com/mugs/nhl/20232024/BUF/8482221.png",
                "name": "D. Levi",
                "sweaterNo": 27,
                "position": "G",
                "goalsAgainstAverage": 2.0,
                "savePctg": 0.943
            },
            {
                "star": 2,
                "playerId": 8482175,
                "teamAbbrev": "BUF",
                "headshot": "https://assets.nhle.com/mugs/nhl/20232024/BUF/8482175.png",
                "name": "J. Peterka",
                "sweaterNo": 77,
                "position": "R",
                "goals": 1,
                "assists": 1,
                "points": 2
            },
            {
                "star": 3,
                "playerId": 8475784,
                "teamAbbrev": "BUF",
                "headshot": "https://assets.nhle.com/mugs/nhl/20232024/BUF/8475784.png",
                "name": "J. Skinner",
                "sweaterNo": 53,
                "position": "L",
                "goals": 1,
                "assists": 1,
                "points": 2
            }
        ],
        "teamGameStats": [
            {
                "category": "sog",
                "awayValue": 35,
                "homeValue": 25
            },
            {
                "category": "faceoffWinningPctg",
                "awayValue": 0.727273,
                "homeValue": 0.272727
            },
            {
                "category": "powerPlay",
                "awayValue": "2/5",
                "homeValue": "0/4"
            },
            {
                "category": "powerPlayPctg",
                "awayValue": 0.4,
                "homeValue": 0.0
            },
            {
                "category": "pim",
                "awayValue": 8,
                "homeValue": 10
            },
            {
                "category": "hits",
                "awayValue": 31,
                "homeValue": 20
            },
            {
                "category": "blockedShots",
                "awayValue": 18,
                "homeValue": 22
            },
            {
                "category": "giveaways",
                "awayValue": 6,
                "homeValue": 6
            },
            {
                "category": "takeaways",
                "awayValue": 6,
                "homeValue": 2
            }
        ]
    },
    "periodDescriptor": {
        "number": 3,
        "periodType": "REG",
        "maxRegulationPeriods": 3
    },
    "clock": {
        "timeRemaining": "00:00",
        "secondsRemaining": 0,
        "running": false,
        "inIntermission": false
    }
}