In [8]:
import pandas as pd
from pathlib import Path

In [2]:
def adjust_df_display(dimension, action):
    """This function when called adjusts the output display of pandas dataframes. It either changes the max_columns or max_rows to infinite or resets those
    values to their default display limits.

    Args:
        dimension (string): Display dimension of a dataframe to alter; should be either "columns" or "rows".
        action (string): Action to be carried out on display settings; should be either "max" or "limit".
    """
    if dimension == "columns" and action == "max":
        pd.set_option('display.max_columns', None)
    elif dimension == "rows" and action == "max":
        pd.set_option('display.max_rows', None)
    elif dimension == "columns" and action == "limit":
        pd.reset_option('max_columns')
    else:
        pd.reset_option('max_rows')

In [3]:
adjust_df_display("columns", "max")
adjust_df_display("rows", "max")

In [15]:
PROJECT_ROOT = Path.cwd().resolve().parents[0]   # Adjust number as needed
DATA_DIR = PROJECT_ROOT / "data"
train_linear = DATA_DIR / "processed/nhl_shots_scaled_for_linear.csv"

# Load raw data
df = pd.read_csv(train_linear)
df.head(30)

,game_id,event_id,sort_order,shooting_team_strength_diff,shooter_id,goalie_id,team_id,shooter_team_abbrev,opponent_team_abbrev,is_home_team,y_coord,is_goal,time_into_period_sec,empty_net_shot,x_coord_log,period_1,period_2,period_3,period_4,period_type_OT,period_type_REG,shooting_team_strength_state_0v1,shooting_team_strength_state_1v0,shooting_team_strength_state_3v3,shooting_team_strength_state_3v4,shooting_team_strength_state_3v5,shooting_team_strength_state_3v6,shooting_team_strength_state_4v3,shooting_team_strength_state_4v4,shooting_team_strength_state_4v5,shooting_team_strength_state_4v6,shooting_team_strength_state_5v3,shooting_team_strength_state_5v4,shooting_team_strength_state_5v5,shooting_team_strength_state_5v6,shooting_team_strength_state_6v3,shooting_team_strength_state_6v4,shooting_team_strength_state_6v5,event_type_goal,event_type_missed-shot,event_type_shot-on-goal,zone_D,zone_N,zone_O,shot_type_backhand,shot_type_bat,shot_type_between-legs,shot_type_cradle,shot_type_deflected,shot_type_poke,shot_type_slap,shot_type_snap,shot_type_tip-in,shot_type_wrap-around,shot_type_wrist,shot_type_nan,miss_reason_above-crossbar,miss_reason_failed-bank-attempt,miss_reason_goalpost,miss_reason_high-and-wide-left,miss_reason_high-and-wide-right,miss_reason_hit-crossbar,miss_reason_hit-left-post,miss_reason_hit-right-post,miss_reason_on-net,miss_reason_over-net,miss_reason_short,miss_reason_wide-left,miss_reason_wide-of-net,miss_reason_wide-right,miss_reason_nan
0,2019020001,10,11,0,8480801,8475883.0,9,OTT,TOR,0,-0.045333,1,-1.641227,0,-1.548198,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2019020001,12,15,0,8479458,8475883.0,9,OTT,TOR,0,-1.908294,0,-1.603908,0,1.286072,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2019020001,15,28,1,8476853,8467950.0,10,TOR,OTT,1,-0.097082,0,-1.451762,0,1.182794,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2019020001,18,33,1,8478483,8467950.0,10,TOR,OTT,1,-0.821567,0,-1.374254,0,0.766270,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2019020001,19,44,0,8478857,8467950.0,10,TOR,OTT,1,-0.200580,0,-1.170436,0,0.033652,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,2019020001,20,45,0,8476331,8475883.0,9,OTT,TOR,0,-0.304078,0,-1.130246,0,0.083158,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2019020001,21,53,0,8476853,8467950.0,10,TOR,OTT,1,-1.028562,0,-1.035514,0,0.268639,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2019020001,23,61,0,8479675,8467950.0,10,TOR,OTT,1,0.213412,0,-0.906333,0,-1.672858,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,2019020001,24,62,0,8475197,8467950.0,10,TOR,OTT,1,-1.494303,0,-0.889109,0,0.895387,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2019020001,25,63,0,8475197,8467950.0,10,TOR,OTT,1,-0.355826,0,-0.871885,0,0.553453,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2019020001,28,69,0,8476879,8467950.0,10,TOR,OTT,1,1.972875,0,-0.762800,0,1.015889,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2019020001,29,71,0,8477341,8467950.0,10,TOR,OTT,1,-0.718069,0,-0.702515,0,-0.698967,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2019020001,31,79,1,8478483,8467950.0,10,TOR,OTT,1,-1.597801,0,-0.673809,0,0.083158,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2019020001,33,80,1,8478483,8467950.0,10,TOR,OTT,1,-1.390805,0,-0.630748,0,-0.069626,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2019020001,36,84,1,8479318,8467950.0,10,TOR,OTT,1,1.041394,0,-0.604912,0,-0.295778,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2019020001,37,90,1,8477939,8467950.0,10,TOR,OTT,1,0.679152,0,-0.475732,0,-0.856184,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2019020001,38,91,1,8475197,8467950.0,10,TOR,OTT,1,1.765879,0,-0.421189,0,1.182794,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2019020001,39,92,1,8477939,8467950.0,10,TOR,OTT,1,-0.200580,0,-0.395353,0,-1.028397,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2019020001,42,101,0,8478400,8475883.0,9,OTT,TOR,0,-0.252329,0,-0.337940,0,-0.856184,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2019020001,43,104,0,8478469,8475883.0,9,OTT,TOR,0,1.196641,0,-0.320715,0,0.732496,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2019020001,45,111,1,8479318,8467950.0,10,TOR,OTT,1,1.248390,0,-0.292009,0,0.033652,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2019020001,46,113,1,8476853,8467950.0,10,TOR,OTT,1,1.248390,0,-0.211630,0,1.015889,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
22,2019020001,47,117,-1,8477407,8475883.0,9,OTT,TOR,0,-0.200580,0,-0.139863,0,-1.322046,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2019020001,48,120,1,8475197,8467950.0,10,TOR,OTT,1,1.610633,0,-0.016424,0,1.073254,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
24,2019020001,49,122,0,8474589,8475883.0,9,OTT,TOR,0,-1.028562,0,0.026636,0,-0.123566,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2019020001,202,127,0,8479458,8475883.0,9,OTT,TOR,0,-1.856545,0,0.043860,0,0.732496,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2019020001,204,135,0,8481624,8467950.0,10,TOR,OTT,1,1.041394,0,0.227584,0,0.131344,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27,2019020001,206,146,0,8477407,8475883.0,9,OTT,TOR,0,1.455386,0,0.417048,0,0.396236,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2019020001,209,154,0,8476853,8467950.0,10,TOR,OTT,1,-2.115290,0,0.520393,0,0.799425,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2019020001,210,156,0,8480801,8475883.0,9,OTT,TOR,0,1.144892,0,0.603642,0,0.627213,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
df.columns

Index(['game_id', 'event_id', 'sort_order', 'shooting_team_strength_diff',
       'shooter_id', 'goalie_id', 'team_id', 'shooter_team_abbrev',
       'opponent_team_abbrev', 'is_home_team', 'y_coord', 'is_goal',
       'time_into_period_sec', 'empty_net_shot', 'x_coord_log', 'period_1',
       'period_2', 'period_3', 'period_4', 'period_type_OT', 'period_type_REG',
       'shooting_team_strength_state_0v1', 'shooting_team_strength_state_1v0',
       'shooting_team_strength_state_3v3', 'shooting_team_strength_state_3v4',
       'shooting_team_strength_state_3v5', 'shooting_team_strength_state_3v6',
       'shooting_team_strength_state_4v3', 'shooting_team_strength_state_4v4',
       'shooting_team_strength_state_4v5', 'shooting_team_strength_state_4v6',
       'shooting_team_strength_state_5v3', 'shooting_team_strength_state_5v4',
       'shooting_team_strength_state_5v5', 'shooting_team_strength_state_5v6',
       'shooting_team_strength_state_6v3', 'shooting_team_strength_state_6v4',
       'shooting_team_strength_state_6v5', 'event_type_goal',
       'event_type_missed-shot', 'event_type_shot-on-goal', 'zone_D', 'zone_N',
       'zone_O', 'shot_type_backhand', 'shot_type_bat',
       'shot_type_between-legs', 'shot_type_cradle', 'shot_type_deflected',
       'shot_type_poke', 'shot_type_slap', 'shot_type_snap',
       'shot_type_tip-in', 'shot_type_wrap-around', 'shot_type_wrist',
       'shot_type_nan', 'miss_reason_above-crossbar',
       'miss_reason_failed-bank-attempt', 'miss_reason_goalpost',
       'miss_reason_high-and-wide-left', 'miss_reason_high-and-wide-right',
       'miss_reason_hit-crossbar', 'miss_reason_hit-left-post',
       'miss_reason_hit-right-post', 'miss_reason_on-net',
       'miss_reason_over-net', 'miss_reason_short', 'miss_reason_wide-left',
       'miss_reason_wide-of-net', 'miss_reason_wide-right', 'miss_reason_nan'],
      dtype='object')

In [27]:
PROJECT_ROOT = Path.cwd().resolve().parents[0]   # Adjust number as needed
DATA_DIR = PROJECT_ROOT / "data"
shots_cleaned = DATA_DIR / "processed/nhl_shots_cleaned.csv"
shots_raw = DATA_DIR / "raw/nhl_shots_2019_2024.csv"
shots_cleaned_features = DATA_DIR / "processed/nhl_shots_cleaned_features.csv"

# Load raw data
df = pd.read_csv(shots_cleaned_features)
#df.head(30)
print(df.columns)

Index(['period', 'period_type', 'shooting_team_strength_state',
       'shooting_team_strength_diff', 'is_home_team', 'event_type', 'x_coord',
       'y_coord', 'zone', 'shot_type', 'is_goal', 'miss_reason',
       'time_into_period_sec', 'empty_net_shot'],
      dtype='object')

In [35]:
PROJECT_ROOT = Path.cwd().resolve().parents[0]   # Adjust number as needed
DATA_DIR = PROJECT_ROOT / "data"
scaled_linear = DATA_DIR / "processed/nhl_shots_scaled_for_linear.csv"
scaled_tree = DATA_DIR / "processed/nhl_shots_scaled_for_tree.csv"

# Load raw data
df = pd.read_csv(scaled_linear)

print(df.columns)
#df.describe()
df.head(30)

Index(['shooting_team_strength_diff', 'is_home_team', 'y_coord', 'is_goal',
       'time_into_period_sec', 'empty_net_shot', 'x_coord_log', 'period_1',
       'period_2', 'period_3', 'period_4', 'period_type_OT', 'period_type_REG',
       'shooting_team_strength_state_0v1', 'shooting_team_strength_state_1v0',
       'shooting_team_strength_state_3v3', 'shooting_team_strength_state_3v4',
       'shooting_team_strength_state_3v5', 'shooting_team_strength_state_3v6',
       'shooting_team_strength_state_4v3', 'shooting_team_strength_state_4v4',
       'shooting_team_strength_state_4v5', 'shooting_team_strength_state_4v6',
       'shooting_team_strength_state_5v3', 'shooting_team_strength_state_5v4',
       'shooting_team_strength_state_5v5', 'shooting_team_strength_state_5v6',
       'shooting_team_strength_state_6v3', 'shooting_team_strength_state_6v4',
       'shooting_team_strength_state_6v5', 'event_type_goal',
       'event_type_missed-shot', 'event_type_shot-on-goal', 'zone_D', 'zone_N',
       'zone_O', 'shot_type_backhand', 'shot_type_bat',
       'shot_type_between-legs', 'shot_type_cradle', 'shot_type_deflected',
       'shot_type_poke', 'shot_type_slap', 'shot_type_snap',
       'shot_type_tip-in', 'shot_type_wrap-around', 'shot_type_wrist',
       'shot_type_nan', 'miss_reason_above-crossbar',
       'miss_reason_failed-bank-attempt', 'miss_reason_goalpost',
       'miss_reason_high-and-wide-left', 'miss_reason_high-and-wide-right',
       'miss_reason_hit-crossbar', 'miss_reason_hit-left-post',
       'miss_reason_hit-right-post', 'miss_reason_on-net',
       'miss_reason_over-net', 'miss_reason_short', 'miss_reason_wide-left',
       'miss_reason_wide-of-net', 'miss_reason_wide-right', 'miss_reason_nan'],
      dtype='object')

,shooting_team_strength_diff,is_home_team,y_coord,is_goal,time_into_period_sec,empty_net_shot,x_coord_log,period_1,period_2,period_3,period_4,period_type_OT,period_type_REG,shooting_team_strength_state_0v1,shooting_team_strength_state_1v0,shooting_team_strength_state_3v3,shooting_team_strength_state_3v4,shooting_team_strength_state_3v5,shooting_team_strength_state_3v6,shooting_team_strength_state_4v3,shooting_team_strength_state_4v4,shooting_team_strength_state_4v5,shooting_team_strength_state_4v6,shooting_team_strength_state_5v3,shooting_team_strength_state_5v4,shooting_team_strength_state_5v5,shooting_team_strength_state_5v6,shooting_team_strength_state_6v3,shooting_team_strength_state_6v4,shooting_team_strength_state_6v5,event_type_goal,event_type_missed-shot,event_type_shot-on-goal,zone_D,zone_N,zone_O,shot_type_backhand,shot_type_bat,shot_type_between-legs,shot_type_cradle,shot_type_deflected,shot_type_poke,shot_type_slap,shot_type_snap,shot_type_tip-in,shot_type_wrap-around,shot_type_wrist,shot_type_nan,miss_reason_above-crossbar,miss_reason_failed-bank-attempt,miss_reason_goalpost,miss_reason_high-and-wide-left,miss_reason_high-and-wide-right,miss_reason_hit-crossbar,miss_reason_hit-left-post,miss_reason_hit-right-post,miss_reason_on-net,miss_reason_over-net,miss_reason_short,miss_reason_wide-left,miss_reason_wide-of-net,miss_reason_wide-right,miss_reason_nan
0,0,0,-0.045333,1,-1.641227,0,-1.548198,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,-1.908294,0,-1.603908,0,1.286072,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1,1,-0.097082,0,-1.451762,0,1.182794,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,1,-0.821567,0,-1.374254,0,0.766270,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0,1,-0.200580,0,-1.170436,0,0.033652,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,0,0,-0.304078,0,-1.130246,0,0.083158,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0,1,-1.028562,0,-1.035514,0,0.268639,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0,1,0.213412,0,-0.906333,0,-1.672858,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,0,1,-1.494303,0,-0.889109,0,0.895387,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0,1,-0.355826,0,-0.871885,0,0.553453,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0,1,1.972875,0,-0.762800,0,1.015889,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0,1,-0.718069,0,-0.702515,0,-0.698967,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1,1,-1.597801,0,-0.673809,0,0.083158,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1,1,-1.390805,0,-0.630748,0,-0.069626,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,1,1,1.041394,0,-0.604912,0,-0.295778,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,1,1,0.679152,0,-0.475732,0,-0.856184,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16,1,1,1.765879,0,-0.421189,0,1.182794,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1,1,-0.200580,0,-0.395353,0,-1.028397,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0,0,-0.252329,0,-0.337940,0,-0.856184,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0,0,1.196641,0,-0.320715,0,0.732496,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1,1,1.248390,0,-0.292009,0,0.033652,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
21,1,1,1.248390,0,-0.211630,0,1.015889,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
22,-1,0,-0.200580,0,-0.139863,0,-1.322046,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
23,1,1,1.610633,0,-0.016424,0,1.073254,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
24,0,0,-1.028562,0,0.026636,0,-0.123566,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0,0,-1.856545,0,0.043860,0,0.732496,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0,1,1.041394,0,0.227584,0,0.131344,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27,0,0,1.455386,0,0.417048,0,0.396236,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0,1,-2.115290,0,0.520393,0,0.799425,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0,0,1.144892,0,0.603642,0,0.627213,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0